/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo54.vistas;

import javax.swing.JOptionPane;
import universidadgrupo54.accesoDatos.MateriaData;
import universidadgrupo54.entidades.MateriaEntidades;

/**
 *
 * @author Pablo
 */
public class MateriaVista extends javax.swing.JInternalFrame {

   private MateriaEntidades mat;
   private MateriaData matD;
    private boolean banderaModificar;

    public MateriaVista() {
        initComponents();
        mat = new MateriaEntidades();
        matD = new MateriaData();
        banderaModificar = false;
    }

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jTNombreMat = new javax.swing.JTextField();
        jTAnio = new javax.swing.JTextField();
        jREstadoMat = new javax.swing.JRadioButton();
        jBNuevoMat = new javax.swing.JButton();
        jBEliminarMat = new javax.swing.JButton();
        jBGuardarMat = new javax.swing.JButton();
        jBSalirMat = new javax.swing.JButton();
        jBBuscarMat = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Materia");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Codigo");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Año");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Estado");

        jTCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jTNombreMat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTNombreMat.setEnabled(false);

        jTAnio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTAnio.setEnabled(false);

        jREstadoMat.setEnabled(false);

        jBNuevoMat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBNuevoMat.setText("Nuevo");
        jBNuevoMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoMatActionPerformed(evt);
            }
        });

        jBEliminarMat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBEliminarMat.setText("Eliminar");
        jBEliminarMat.setEnabled(false);
        jBEliminarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarMatActionPerformed(evt);
            }
        });

        jBGuardarMat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBGuardarMat.setText("Guardar");
        jBGuardarMat.setEnabled(false);
        jBGuardarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarMatActionPerformed(evt);
            }
        });

        jBSalirMat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBSalirMat.setText("Salir");
        jBSalirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirMatActionPerformed(evt);
            }
        });

        jBBuscarMat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBBuscarMat.setText("Buscar");
        jBBuscarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMatActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jBNuevoMat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jREstadoMat)
                                    .addGap(244, 244, 244)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                                .addGap(49, 49, 49)
                                .addComponent(jBBuscarMat))
                            .addComponent(jTNombreMat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardarMat)
                        .addGap(30, 30, 30)
                        .addComponent(jBEliminarMat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBSalirMat)))
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(310, 310, 310))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBCancelar)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarMat))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jREstadoMat)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jBCancelar)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevoMat)
                    .addComponent(jBGuardarMat)
                    .addComponent(jBEliminarMat)
                    .addComponent(jBSalirMat))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // ELIMINAR METODO
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jBBuscarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMatActionPerformed
        
        
        
        int codigo = Integer.parseInt(jTCodigo.getText());
        MateriaEntidades mat = matD.buscarMateria(codigo);
        
         jTNombreMat.setEnabled(true);
        jTAnio.setEnabled(true);
        jREstadoMat.setEnabled(true);
        banderaModificar = true;
        jREstadoMat.setSelected(true);
        jBGuardarMat.setEnabled(true);
        jBEliminarMat.setEnabled(true);
        jTNombreMat.setText(mat.getNombre());
        jTAnio.setText(mat.getAnio());
        jTCodigo.setEnabled(false);
        jBBuscarMat.setEnabled(false);
        jBCancelar.setEnabled(true);
    }//GEN-LAST:event_jBBuscarMatActionPerformed

    private void jBNuevoMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoMatActionPerformed
        jTCodigo.setEnabled(false);
        jTAnio.setEnabled(true);
        jTNombreMat.setEnabled(true);
        jBGuardarMat.setEnabled(true);
        limpiarCampos();
        jREstadoMat.setSelected(true);
        jREstadoMat.setEnabled(false);
        banderaModificar = false;
        jBCancelar.setEnabled(true);
        jBEliminarMat.setEnabled(false);
        

    }//GEN-LAST:event_jBNuevoMatActionPerformed

    private void jBGuardarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarMatActionPerformed
        jREstadoMat.setSelected(false);
        

        if (mat.getNombre() == jTNombreMat.getText()) {
            mensaje("Esa materia ya existe");
            
        } else if (!banderaModificar) {
            
            String nombre = jTNombreMat.getText();
            String anio = jTAnio.getText();
            MateriaEntidades mat = new MateriaEntidades(nombre, anio, true);
            matD.guardarMateria(mat);
            
          } else {
             
            MateriaEntidades mat = new MateriaEntidades();
           
            mat.setNombre(jTNombreMat.getText());
            mat.setAnio(jTAnio.getText());
            mat.setIdMateria(Integer.parseInt(jTCodigo.getText()));
            matD.modificarMateria(mat);
        }
        limpiarCampos();
        jBBuscarMat.setEnabled(true);
        jTCodigo.setEnabled(true);
        jTNombreMat.setEnabled(false);
        jTAnio.setEnabled(false);
        jREstadoMat.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBEliminarMat.setEnabled(false);
        jBGuardarMat.setEnabled(false);
    }//GEN-LAST:event_jBGuardarMatActionPerformed

    private void jBEliminarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarMatActionPerformed
        int idMateria = Integer.parseInt(jTCodigo.getText());
        matD.eliminarMateria(idMateria);
        limpiarCampos();
         jBBuscarMat.setEnabled(true);
        jTCodigo.setEnabled(true);
        jTNombreMat.setEnabled(false);
        jTAnio.setEnabled(false);
        jREstadoMat.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBEliminarMat.setEnabled(false);
        jBGuardarMat.setEnabled(false);
        
    }//GEN-LAST:event_jBEliminarMatActionPerformed

    private void jBSalirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirMatActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirMatActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
   
         limpiarCampos();
        jBBuscarMat.setEnabled(true);
        jTCodigo.setEnabled(true);
        jTNombreMat.setEnabled(false);
        jTAnio.setEnabled(false);
        jREstadoMat.setEnabled(false);
        jBCancelar.setEnabled(false);
        jBEliminarMat.setEnabled(false);
        jBGuardarMat.setEnabled(false);
        
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void limpiarCampos() {
        jTCodigo.setText("");
        jTNombreMat.setText("");
        jTAnio.setText("");
        jREstadoMat.setSelected(false);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarMat;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBEliminarMat;
    private javax.swing.JButton jBGuardarMat;
    private javax.swing.JButton jBNuevoMat;
    private javax.swing.JButton jBSalirMat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jREstadoMat;
    private javax.swing.JTextField jTAnio;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTNombreMat;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
